export default {
  es_extended: "es_extended",
  esx_lib: "esx_lib",
  esx_context: "Context",
  esx_identity: "Identity",
  esx_inventory: "Inventory",
  esx_menu_default: "Menu Default",
  esx_menu_dialog: "Menu Dialog",
  esx_menu_list: "Menu List",
  esx_multicharacter: "Multicharacter",
  esx_notify: "Notify",
  esx_progressbar: "Progressbar",
  esx_skin: "Skin",
  esx_textui: "Text UI",
  skinchanger: "Skinchanger",
  cron: "Cron",
  esx_loadingscreen: "Loadingscreen",
  esx_chat_theme: "Chat Theme",
};
