export default {
    esx_shops: "Shops",
    esx_weaponshop: "Weapon Shop",
    esx_clotheshop: "Clothes Shop",
    esx_vehicleshop: "Vehicle Shop",
    esx_accessories: "Accessories",
    esx_hud: "HUD",
    esx_garage: "Garage",
    esx_property: "Property",
    esx_addonaccount: "Addon Account",
    esx_addoninventory: "Addon Inventory",
    esx_ambulancejob: "Ambulance Job",
    esx_mechanicjob: "Mechanic Job",
    esx_policejob: "Police Job",
    esx_animations: "Animations",
    esx_banking: "Banking",
    esx_barbershop: "Barbershop",
    esx_basicneeds: "Basic Needs",
    esx_billing: "Billing",
    esx_boat: "Boat",
    esx_dmvschool: "DMV School",
    esx_drugs: "Drugs",
    esx_jobs: "Jobs",
    esx_license: "License",
    esx_status: "Status",
    esx_taxijob: "Taxi Job",
    esx_service: "Service",
    esx_society: "Society",
    esx_rpchat: "RP Chat",
    esx_joblisting: "Job Listing",
    esx_cruisecontrol: "Cruise Control",
    esx_lscustom: "LS Custom",
    esx_datastore: "Datastore",
    esx_optionalneeds: "Optional Needs",
    esx_adminmenu: "Admin Menu",
    esx_weather: "Weather",
    esx_scoreboard: "Scoreboard",

};
